# ========== FEEDS ESPAÑOLES ==========
feeds_espanoles = {
    "El País": "https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/portada",
    "El Mundo": "https://e00-elmundo.uecdn.es/elmundo/rss/portada.xml",
    "ABC": "https://www.abc.es/rss/feeds/abcPortada.xml",
    "La Vanguardia": "https://www.lavanguardia.com/rss/home.xml",
    "20 Minutos": "https://www.20minutos.es/feed/",
    "eldiario.es": "https://www.eldiario.es/rss/",
    "Europa Press": "https://www.europapress.es/rss/rss.aspx",
    "El Español": "https://www.elespanol.com/rss/",
    "RTVE": "https://www.rtve.es/rss/",
    "El Confidencial": "https://www.elconfidencial.com/rss/",
    "Público": "https://www.publico.es/rss/",
    "HuffPost": "https://www.huffingtonpost.es/feeds/index.xml",
    "La Voz de Galicia": "https://www.lavozdegalicia.es/rss/portada.xml",
    "El Correo": "https://www.elcorreo.com/rss/portada.xml",
    "Diario Sur": "https://www.diariosur.es/rss/portada.xml",
    "Levante": "https://www.levante-emv.com/rss/portada.xml",
    "Heraldo": "https://www.heraldo.es/rss/portada/",
    "Diario Vasco": "https://www.diariovasco.com/rss/portada.xml",
    "Información Alicante": "https://www.informacion.es/rss/portada.xml",
    "Expansión": "https://e00-expansion.uecdn.es/rss/portada.xml",
    "Cinco Días": "https://cincodias.elpais.com/seccion/rss/portada/",
    "Infolibre": "https://www.infolibre.es/rss",
    "El Salto": "https://www.elsaltodiario.com/rss",
    "CTXT": "https://ctxt.es/es/feed/",
    "Jacobin ES": "https://jacobin.com/feed",
    "Infobae España": "https://www.infobae.com/espana/arc/outboundfeeds/rss/",
    "OK Diario": "https://okdiario.com/feed/",
    "El Plural": "https://www.elplural.com/feed",
    "Vozpópuli": "https://www.vozpopuli.com/feed.xml",
    "Moncloa.com": "https://www.moncloa.com/feed",
    "El Independiente": "https://www.elindependiente.com/feed",
    "The Objective": "https://theobjective.com/feed",
    "Crónica Global": "https://cronicaglobal.elespanol.com/feed",
    "El Debate": "https://www.eldebate.com/feed",
    "Libertad Digital": "https://www.libertaddigital.com/feed",
    "El Periódico de España": "https://www.epe.es/es/rss/portada.xml",
    "Xataka": "https://www.xataka.com/feedburner.xml",
    "Genbeta": "https://www.genbeta.com/feedburner.xml",
    "Trendencias": "https://www.trendencias.com/feedburner.xml",
    "Verne": "https://feeds.elpais.com/mrss-s/pages/ep/site/verne.elpais.com/portada",
    "Yorokobu": "https://www.yorokobu.es/feed/",
    "El Periódico": "https://www.elperiodico.com/es/rss/rss_portada.xml",
    "Hipertextual": "https://hipertextual.com/feed",
    "Microsiervos": "https://www.microsiervos.com/index.xml",
    "OpenDemocracy": "https://www.opendemocracy.net/en/rss.xml",
    "RT en Español": "https://actualidad.rt.com/feeds/noticias.rss",
    "Applesfera": "https://www.applesfera.com/feedburner.xml",
}

feeds_internacionales = {
    "Scientific American": "https://rss.sciam.com/ScientificAmerican-Global",
    "Politico EU": "https://www.politico.eu/feed/",
    "BBC World": "https://feeds.bbci.co.uk/news/world/rss.xml",
    "CNN World": "http://rss.cnn.com/rss/edition_world.rss",
    "Reuters": "https://www.reutersagency.com/feed/?best-topics=world",
    "NYTimes": "https://rss.nytimes.com/services/xml/rss/nyt/World.xml",
    "Guardian": "https://www.theguardian.com/world/rss",
    "Bloomberg": "https://feeds.bloomberg.com/markets/news.rss",
    "Financial Times": "https://www.ft.com/world?format=rss",
    "RT News": "https://www.rt.com/rss/news/",
    "Le Monde": "https://www.lemonde.fr/rss/une.xml",
    "France24 FR": "https://www.france24.com/fr/rss",
    "Le Figaro": "https://www.lefigaro.fr/rss/figaro_actualites.xml",
    "Der Spiegel": "https://www.spiegel.de/international/index.rss",
    "Die Welt": "https://www.welt.de/feeds/latest.rss",
    "Corriere": "https://xml2.corriereobjects.it/rss/homepage.xml",
    "La Repubblica": "https://www.repubblica.it/rss/homepage/rss2.0.xml",
    "Publico PT": "https://www.publico.pt/rss",
    "TASS": "http://tass.com/rss/v2.xml",
    "Yonhap News": "https://en.yna.co.kr/feed/",
    "Korea Times": "https://www.koreatimes.co.kr/www/rss/news.xml",
    "Korea Herald": "http://www.koreaherald.com/rss_xml.php",
    "Arirang News": "https://www.arirang.com/news/rss.xml",
    "Al Jazeera English": "https://www.aljazeera.com/xml/rss/all.xml",
    "Al Arabiya English": "https://english.alarabiya.net/alarabiya-rss",
    "Middle East Eye": "https://www.middleeasteye.net/rss",
    "The National": "https://www.thenationalnews.com/arc/outboundfeeds/rss/",
    "Arab News": "https://www.arabnews.com/rss",
    "KBS World": "http://world.kbs.co.kr/feed/",
    "MBC News": "http://imnews.imbc.com/rss/news.xml",
    "Al Jazeera (Árabe)": "https://www.aljazeera.net/aljazeerarss/a7c186e5-2c6f-46e3-8782-3d64c6b721a6/7f7b6d64-2f6f-4b6c-9d8e-1f7f3b8c9d0a",
    "Al Mayadeen": "https://english.almayadeen.net/rss",
    "Al Araby": "https://www.alaraby.co.uk/rss",
    "Euronews": "https://www.euronews.com/rss?level=theme&name=news",
    "SCMP Hong Kong": "https://www.scmp.com/rss/91/feed",
    "Japan Times": "https://www.japantimes.co.jp/feed/",
    "China Daily": "http://www.chinadaily.com.cn/rss/world_rss.xml",
    "El Tiempo CO": "https://www.eltiempo.com/rss/colombia.xml",
    "Granma": "http://www.granma.cu/feed",
    "Nature News": "https://www.nature.com/nature.rss",
    "Cubadebate": "http://www.cubadebate.cu/feed/",
    "Prensa Latina": "https://www.prensa-latina.cu/feed/",
    "Infobae América": "https://www.infobae.com/america/arc/outboundfeeds/rss/",
    "El Universal MX": "https://www.eluniversal.com.mx/rss",
    "El Comercio PE": "https://elcomercio.pe/arc/outboundfeeds/rss/",
    "El Nuevo Día (Puerto Rico)": "https://www.elnuevodia.com/rss/",
    "El Universal (Venezuela)": "https://www.eluniversal.com/rss/",
    "The Hindu (India)": "https://www.thehindu.com/news/feeder/default.rss",
    "Times of India": "https://timesofindia.indiatimes.com/rssfeedstopstories.cms"
}
